
# Setup
title:               PrebidLab
email:               rapidcodelab.mx@gmail.com
tagline:             Opensource header bidding server side solution
url:                 "https://prebidlab.online" # insert your site's URL
baseurl:             ""

# About/contact
author: # you can edit these to be your personal details
  name:              Pavel Sanikovich
  url:               https://twitter.com/3rdwave_themes
  email:

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Social
github_username: 
twitter_username: 
instagram_username: 
facebook: 
linkedin_username: 
dribbble_username: 

# Custom vars
version:             1.0.1
github:
  repo:              

# Gems - Dependencies for this theme
gems:
  # None currently

# Build settings
markdown:     kramdown
permalink:    pretty

widgets:
  - title: About
    url: about
    archor: true
  - title: Features
    url: features
    archor: true
  - title: Docs
    url: docs
    archor: true
  - title: License
    url: license
    archor: true
  - title: Contact
    url: contact
    archor: true
